/**
 * Shotstack
 * Official Node SDK for the Shotstack Cloud Video Editing API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FlipTransformation model module.
 * @module model/FlipTransformation
 * @version 0.2.6
 */
class FlipTransformation {
    /**
     * Constructs a new <code>FlipTransformation</code>.
     * Flip a clip vertically or horizontally. Acts as a mirror effect of the clip along the selected plane.
     * @alias module:model/FlipTransformation
     */
    constructor() { 
        
        FlipTransformation.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FlipTransformation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FlipTransformation} obj Optional instance to populate.
     * @return {module:model/FlipTransformation} The populated <code>FlipTransformation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FlipTransformation();

            if (data.hasOwnProperty('horizontal')) {
                obj['horizontal'] = ApiClient.convertToType(data['horizontal'], 'Boolean');
            }
            if (data.hasOwnProperty('vertical')) {
                obj['vertical'] = ApiClient.convertToType(data['vertical'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FlipTransformation</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FlipTransformation</code>.
     */
    static validateJSON(data) {

        return true;
    }

/**
     * Returns Flip a clip horizontally.
     * @return {Boolean}
     */
    getHorizontal() {
        return this.horizontal;
    }

    /**
     * Sets Flip a clip horizontally.
     * @param {Boolean} horizontal Flip a clip horizontally.
     */
    setHorizontal(horizontal) {
        this['horizontal'] = horizontal;
        return this;
    }
/**
     * Returns Flip a clip vertically.
     * @return {Boolean}
     */
    getVertical() {
        return this.vertical;
    }

    /**
     * Sets Flip a clip vertically.
     * @param {Boolean} vertical Flip a clip vertically.
     */
    setVertical(vertical) {
        this['vertical'] = vertical;
        return this;
    }

}



/**
 * Flip a clip horizontally.
 * @member {Boolean} horizontal
 */
FlipTransformation.prototype['horizontal'] = undefined;

/**
 * Flip a clip vertically.
 * @member {Boolean} vertical
 */
FlipTransformation.prototype['vertical'] = undefined;






export default FlipTransformation;

