"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = void 0;
var _ApiClient = _interopRequireDefault(require("../ApiClient"));
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { "default": obj }; }
function _typeof(o) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (o) { return typeof o; } : function (o) { return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o; }, _typeof(o); }
function _createForOfIteratorHelper(o, allowArrayLike) { var it = typeof Symbol !== "undefined" && o[Symbol.iterator] || o["@@iterator"]; if (!it) { if (Array.isArray(o) || (it = _unsupportedIterableToArray(o)) || allowArrayLike && o && typeof o.length === "number") { if (it) o = it; var i = 0; var F = function F() {}; return { s: F, n: function n() { if (i >= o.length) return { done: true }; return { done: false, value: o[i++] }; }, e: function e(_e) { throw _e; }, f: F }; } throw new TypeError("Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method."); } var normalCompletion = true, didErr = false, err; return { s: function s() { it = it.call(o); }, n: function n() { var step = it.next(); normalCompletion = step.done; return step; }, e: function e(_e2) { didErr = true; err = _e2; }, f: function f() { try { if (!normalCompletion && it["return"] != null) it["return"](); } finally { if (didErr) throw err; } } }; }
function _unsupportedIterableToArray(o, minLen) { if (!o) return; if (typeof o === "string") return _arrayLikeToArray(o, minLen); var n = Object.prototype.toString.call(o).slice(8, -1); if (n === "Object" && o.constructor) n = o.constructor.name; if (n === "Map" || n === "Set") return Array.from(o); if (n === "Arguments" || /^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(n)) return _arrayLikeToArray(o, minLen); }
function _arrayLikeToArray(arr, len) { if (len == null || len > arr.length) len = arr.length; for (var i = 0, arr2 = new Array(len); i < len; i++) arr2[i] = arr[i]; return arr2; }
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }
function _defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, _toPropertyKey(descriptor.key), descriptor); } }
function _createClass(Constructor, protoProps, staticProps) { if (protoProps) _defineProperties(Constructor.prototype, protoProps); if (staticProps) _defineProperties(Constructor, staticProps); Object.defineProperty(Constructor, "prototype", { writable: false }); return Constructor; }
function _toPropertyKey(t) { var i = _toPrimitive(t, "string"); return "symbol" == _typeof(i) ? i : i + ""; }
function _toPrimitive(t, r) { if ("object" != _typeof(t) || !t) return t; var e = t[Symbol.toPrimitive]; if (void 0 !== e) { var i = e.call(t, r || "default"); if ("object" != _typeof(i)) return i; throw new TypeError("@@toPrimitive must return a primitive value."); } return ("string" === r ? String : Number)(t); } /**
 * Shotstack
 * Official Node SDK for the Shotstack Cloud Video Editing API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * The GoogleCloudStorageDestinationOptions model module.
 * @module model/GoogleCloudStorageDestinationOptions
 * @version 0.2.6
 */
var GoogleCloudStorageDestinationOptions = /*#__PURE__*/function () {
  /**
   * Constructs a new <code>GoogleCloudStorageDestinationOptions</code>.
   * Pass additional options to control how files are stored in Google Cloud Storage.
   * @alias module:model/GoogleCloudStorageDestinationOptions
   * @param bucket {String} The bucket name to send files to. The bucket must exist in the Google Cloud Storage account before files can be sent.
   */
  function GoogleCloudStorageDestinationOptions(bucket) {
    _classCallCheck(this, GoogleCloudStorageDestinationOptions);
    GoogleCloudStorageDestinationOptions.initialize(this, bucket);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  return _createClass(GoogleCloudStorageDestinationOptions, [{
    key: "getBucket",
    value:
    /**
         * Returns The bucket name to send files to. The bucket must exist in the Google Cloud Storage account before files can be sent.
         * @return {String}
         */
    function getBucket() {
      return this.bucket;
    }

    /**
     * Sets The bucket name to send files to. The bucket must exist in the Google Cloud Storage account before files can be sent.
     * @param {String} bucket The bucket name to send files to. The bucket must exist in the Google Cloud Storage account before files can be sent.
     */
  }, {
    key: "setBucket",
    value: function setBucket(bucket) {
      this['bucket'] = bucket;
      return this;
    }
    /**
         * Returns A prefix for the file being sent. This is typically a folder name, i.e. `videos` or `customerId/videos`.
         * @return {String}
         */
  }, {
    key: "getPrefix",
    value: function getPrefix() {
      return this.prefix;
    }

    /**
     * Sets A prefix for the file being sent. This is typically a folder name, i.e. `videos` or `customerId/videos`.
     * @param {String} prefix A prefix for the file being sent. This is typically a folder name, i.e. `videos` or `customerId/videos`.
     */
  }, {
    key: "setPrefix",
    value: function setPrefix(prefix) {
      this['prefix'] = prefix;
      return this;
    }
    /**
         * Returns Use your own filename instead of the default filenames generated by Shotstack. Note: omit the file extension as this will be appended depending on the output format. Also `-poster.jpg` and `-thumb.jpg` will be appended for poster and thumbnail images.
         * @return {String}
         */
  }, {
    key: "getFilename",
    value: function getFilename() {
      return this.filename;
    }

    /**
     * Sets Use your own filename instead of the default filenames generated by Shotstack. Note: omit the file extension as this will be appended depending on the output format. Also `-poster.jpg` and `-thumb.jpg` will be appended for poster and thumbnail images.
     * @param {String} filename Use your own filename instead of the default filenames generated by Shotstack. Note: omit the file extension as this will be appended depending on the output format. Also `-poster.jpg` and `-thumb.jpg` will be appended for poster and thumbnail images.
     */
  }, {
    key: "setFilename",
    value: function setFilename(filename) {
      this['filename'] = filename;
      return this;
    }
  }], [{
    key: "initialize",
    value: function initialize(obj, bucket) {
      obj['bucket'] = bucket;
    }

    /**
     * Constructs a <code>GoogleCloudStorageDestinationOptions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GoogleCloudStorageDestinationOptions} obj Optional instance to populate.
     * @return {module:model/GoogleCloudStorageDestinationOptions} The populated <code>GoogleCloudStorageDestinationOptions</code> instance.
     */
  }, {
    key: "constructFromObject",
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new GoogleCloudStorageDestinationOptions();
        if (data.hasOwnProperty('bucket')) {
          obj['bucket'] = _ApiClient["default"].convertToType(data['bucket'], 'String');
        }
        if (data.hasOwnProperty('prefix')) {
          obj['prefix'] = _ApiClient["default"].convertToType(data['prefix'], 'String');
        }
        if (data.hasOwnProperty('filename')) {
          obj['filename'] = _ApiClient["default"].convertToType(data['filename'], 'String');
        }
      }
      return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GoogleCloudStorageDestinationOptions</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GoogleCloudStorageDestinationOptions</code>.
     */
  }, {
    key: "validateJSON",
    value: function validateJSON(data) {
      // check to make sure all required properties are present in the JSON string
      var _iterator = _createForOfIteratorHelper(GoogleCloudStorageDestinationOptions.RequiredProperties),
        _step;
      try {
        for (_iterator.s(); !(_step = _iterator.n()).done;) {
          var property = _step.value;
          if (!data.hasOwnProperty(property)) {
            throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
          }
        }
        // ensure the json data is a string
      } catch (err) {
        _iterator.e(err);
      } finally {
        _iterator.f();
      }
      if (data['bucket'] && !(typeof data['bucket'] === 'string' || data['bucket'] instanceof String)) {
        throw new Error("Expected the field `bucket` to be a primitive type in the JSON string but got " + data['bucket']);
      }
      // ensure the json data is a string
      if (data['prefix'] && !(typeof data['prefix'] === 'string' || data['prefix'] instanceof String)) {
        throw new Error("Expected the field `prefix` to be a primitive type in the JSON string but got " + data['prefix']);
      }
      // ensure the json data is a string
      if (data['filename'] && !(typeof data['filename'] === 'string' || data['filename'] instanceof String)) {
        throw new Error("Expected the field `filename` to be a primitive type in the JSON string but got " + data['filename']);
      }
      return true;
    }
  }]);
}();
GoogleCloudStorageDestinationOptions.RequiredProperties = ["bucket"];

/**
 * The bucket name to send files to. The bucket must exist in the Google Cloud Storage account before files can be sent.
 * @member {String} bucket
 */
GoogleCloudStorageDestinationOptions.prototype['bucket'] = undefined;

/**
 * A prefix for the file being sent. This is typically a folder name, i.e. `videos` or `customerId/videos`.
 * @member {String} prefix
 */
GoogleCloudStorageDestinationOptions.prototype['prefix'] = undefined;

/**
 * Use your own filename instead of the default filenames generated by Shotstack. Note: omit the file extension as this will be appended depending on the output format. Also `-poster.jpg` and `-thumb.jpg` will be appended for poster and thumbnail images.
 * @member {String} filename
 */
GoogleCloudStorageDestinationOptions.prototype['filename'] = undefined;
var _default = exports["default"] = GoogleCloudStorageDestinationOptions;