/**
 * Shotstack
 * Shotstack is a video, image and audio editing service that allows for the automated generation of videos, images and audio using JSON and a RESTful API.  You arrange and configure an edit and POST it to the API which will render your media and provide a file location when complete.  For more details visit [shotstack.io](https://shotstack.io) or checkout our [getting started](https://shotstack.io/docs/guide/) documentation.  There are three API's, one for editing and generating assets (Edit API), one for managing hosted assets (Serve API) and one for ingesting and transforming source assets (Ingest API).  Each API has it's own base URL and collection of endpoints. Each API uses the same set of API keys.  **[Edit API](#shotstack-edit)** - [https://api.shotstack.io/edit/{version}](#)<br> Edit videos, images and audio assets in the cloud using a simple JSON schema and templates.  **[Serve API](#shotstack-serve)** - [https://api.shotstack.io/serve/{version}](#)<br> Inspect and manage the hosting of assets generated by the Edit and Ingest APIs.  **[Ingest API](#shotstack-ingest)** - [https://api.shotstack.io/ingest/{version}](#)<br> Ingest (upload, store and transform) source footage, images, audio and fonts to be used by the Edit API.  **[Create API](#shotstack-create)** - [https://api.shotstack.io/create/{version}](#)<br> Generate images, videos, voice overs and text using built in and third party generative AI providers. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Crop from './Crop';

/**
 * The ImageAsset model module.
 * @module model/ImageAsset
 * @version 0.2.6
 */
class ImageAsset {
    /**
     * Constructs a new <code>ImageAsset</code>.
     * The ImageAsset is used to create video from images to compose an image. The src must be a publicly accessible URL to an image resource such as a jpg or png file.
     * @alias module:model/ImageAsset
     * @param type {String} The type of asset - set to `image` for images.
     * @param src {String} The image source URL. The URL must be publicly accessible or include credentials.
     */
    constructor(type, src) { 
        
        ImageAsset.initialize(this, type, src);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, src) { 
        obj['type'] = type || 'image';
        obj['src'] = src;
    }

    /**
     * Constructs a <code>ImageAsset</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ImageAsset} obj Optional instance to populate.
     * @return {module:model/ImageAsset} The populated <code>ImageAsset</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ImageAsset();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('src')) {
                obj['src'] = ApiClient.convertToType(data['src'], 'String');
            }
            if (data.hasOwnProperty('crop')) {
                obj['crop'] = Crop.constructFromObject(data['crop']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ImageAsset</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ImageAsset</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ImageAsset.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['src'] && !(typeof data['src'] === 'string' || data['src'] instanceof String)) {
            throw new Error("Expected the field `src` to be a primitive type in the JSON string but got " + data['src']);
        }
        // validate the optional field `crop`
        if (data['crop']) { // data not null
          Crop.validateJSON(data['crop']);
        }

        return true;
    }

/**
     * Returns The type of asset - set to `image` for images.
     * @return {String}
     */
    getType() {
        return this.type;
    }

    /**
     * Sets The type of asset - set to `image` for images.
     * @param {String} type The type of asset - set to `image` for images.
     */
    setType(type) {
        this['type'] = type;
        return this;
    }
/**
     * Returns The image source URL. The URL must be publicly accessible or include credentials.
     * @return {String}
     */
    getSrc() {
        return this.src;
    }

    /**
     * Sets The image source URL. The URL must be publicly accessible or include credentials.
     * @param {String} src The image source URL. The URL must be publicly accessible or include credentials.
     */
    setSrc(src) {
        this['src'] = src;
        return this;
    }
/**
     * @return {module:model/Crop}
     */
    getCrop() {
        return this.crop;
    }

    /**
     * @param {module:model/Crop} crop
     */
    setCrop(crop) {
        this['crop'] = crop;
        return this;
    }

}

ImageAsset.RequiredProperties = ["type", "src"];

/**
 * The type of asset - set to `image` for images.
 * @member {String} type
 * @default 'image'
 */
ImageAsset.prototype['type'] = 'image';

/**
 * The image source URL. The URL must be publicly accessible or include credentials.
 * @member {String} src
 */
ImageAsset.prototype['src'] = undefined;

/**
 * @member {module:model/Crop} crop
 */
ImageAsset.prototype['crop'] = undefined;






export default ImageAsset;

