/**
 * Shotstack
 * Official Node SDK for the Shotstack Cloud Video Editing API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MuxDestinationOptions from './MuxDestinationOptions';

/**
 * The MuxDestination model module.
 * @module model/MuxDestination
 * @version 0.2.6
 */
class MuxDestination {
    /**
     * Constructs a new <code>MuxDestination</code>.
     * Send videos to the [Mux](https://shotstack.io/docs/guide/serving-assets/destinations/mux/) video hosting and streaming service. Mux credentials are required and added via the [dashboard](https://dashboard.shotstack.io/integrations/mux), not in the request.
     * @alias module:model/MuxDestination
     * @param provider {String} The destination to send video to - set to `mux` for Mux.
     */
    constructor(provider) { 
        
        MuxDestination.initialize(this, provider);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, provider) { 
        obj['provider'] = provider || 'mux';
    }

    /**
     * Constructs a <code>MuxDestination</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MuxDestination} obj Optional instance to populate.
     * @return {module:model/MuxDestination} The populated <code>MuxDestination</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MuxDestination();

            if (data.hasOwnProperty('provider')) {
                obj['provider'] = ApiClient.convertToType(data['provider'], 'String');
            }
            if (data.hasOwnProperty('options')) {
                obj['options'] = MuxDestinationOptions.constructFromObject(data['options']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MuxDestination</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MuxDestination</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MuxDestination.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['provider'] && !(typeof data['provider'] === 'string' || data['provider'] instanceof String)) {
            throw new Error("Expected the field `provider` to be a primitive type in the JSON string but got " + data['provider']);
        }
        // validate the optional field `options`
        if (data['options']) { // data not null
          MuxDestinationOptions.validateJSON(data['options']);
        }

        return true;
    }

/**
     * Returns The destination to send video to - set to `mux` for Mux.
     * @return {String}
     */
    getProvider() {
        return this.provider;
    }

    /**
     * Sets The destination to send video to - set to `mux` for Mux.
     * @param {String} provider The destination to send video to - set to `mux` for Mux.
     */
    setProvider(provider) {
        this['provider'] = provider;
        return this;
    }
/**
     * @return {module:model/MuxDestinationOptions}
     */
    getOptions() {
        return this.options;
    }

    /**
     * @param {module:model/MuxDestinationOptions} options
     */
    setOptions(options) {
        this['options'] = options;
        return this;
    }

}

MuxDestination.RequiredProperties = ["provider"];

/**
 * The destination to send video to - set to `mux` for Mux.
 * @member {String} provider
 * @default 'mux'
 */
MuxDestination.prototype['provider'] = 'mux';

/**
 * @member {module:model/MuxDestinationOptions} options
 */
MuxDestination.prototype['options'] = undefined;






export default MuxDestination;

