/**
 * Shotstack
 * Official Node SDK for the Shotstack Cloud Video Editing API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RenditionResponseAttributes from './RenditionResponseAttributes';

/**
 * The OutputsResponse model module.
 * @module model/OutputsResponse
 * @version 0.2.6
 */
class OutputsResponse {
    /**
     * Constructs a new <code>OutputsResponse</code>.
     * The list of outputs generated from the source file. Currently supports renditions which are versions of the source file with different transformations applied.
     * @alias module:model/OutputsResponse
     */
    constructor() { 
        
        OutputsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OutputsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OutputsResponse} obj Optional instance to populate.
     * @return {module:model/OutputsResponse} The populated <code>OutputsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OutputsResponse();

            if (data.hasOwnProperty('renditions')) {
                obj['renditions'] = ApiClient.convertToType(data['renditions'], [RenditionResponseAttributes]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OutputsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OutputsResponse</code>.
     */
    static validateJSON(data) {
        if (data['renditions']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['renditions'])) {
                throw new Error("Expected the field `renditions` to be an array in the JSON data but got " + data['renditions']);
            }
            // validate the optional field `renditions` (array)
            for (const item of data['renditions']) {
                RenditionResponseAttributes.validateJSON(item);
            };
        }

        return true;
    }

/**
     * Returns The list of renditions generated from the source file.
     * @return {Array.<module:model/RenditionResponseAttributes>}
     */
    getRenditions() {
        return this.renditions;
    }

    /**
     * Sets The list of renditions generated from the source file.
     * @param {Array.<module:model/RenditionResponseAttributes>} renditions The list of renditions generated from the source file.
     */
    setRenditions(renditions) {
        this['renditions'] = renditions;
        return this;
    }

}



/**
 * The list of renditions generated from the source file.
 * @member {Array.<module:model/RenditionResponseAttributes>} renditions
 */
OutputsResponse.prototype['renditions'] = undefined;






export default OutputsResponse;

