/**
 * Shotstack
 * Shotstack is a video, image and audio editing service that allows for the automated generation of videos, images and audio using JSON and a RESTful API.  You arrange and configure an edit and POST it to the API which will render your media and provide a file location when complete.  For more details visit [shotstack.io](https://shotstack.io) or checkout our [getting started](https://shotstack.io/docs/guide/) documentation.  There are three API's, one for editing and generating assets (Edit API), one for managing hosted assets (Serve API) and one for ingesting and transforming source assets (Ingest API).  Each API has it's own base URL and collection of endpoints. Each API uses the same set of API keys.  **[Edit API](#shotstack-edit)** - [https://api.shotstack.io/edit/{version}](#)<br> Edit videos, images and audio assets in the cloud using a simple JSON schema and templates.  **[Serve API](#shotstack-serve)** - [https://api.shotstack.io/serve/{version}](#)<br> Inspect and manage the hosting of assets generated by the Edit and Ingest APIs.  **[Ingest API](#shotstack-ingest)** - [https://api.shotstack.io/ingest/{version}](#)<br> Ingest (upload, store and transform) source footage, images, audio and fonts to be used by the Edit API.  **[Create API](#shotstack-create)** - [https://api.shotstack.io/create/{version}](#)<br> Generate images, videos, voice overs and text using built in and third party generative AI providers. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The QueuedResponseData model module.
 * @module model/QueuedResponseData
 * @version 0.2.6
 */
class QueuedResponseData {
    /**
     * Constructs a new <code>QueuedResponseData</code>.
     * The response data returned with the [QueuedResponse](#tocs_queuedresponse).
     * @alias module:model/QueuedResponseData
     * @param message {String} Success response message or error details.
     * @param id {String} The id of the render task in UUID format.
     */
    constructor(message, id) { 
        
        QueuedResponseData.initialize(this, message, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, message, id) { 
        obj['message'] = message;
        obj['id'] = id;
    }

    /**
     * Constructs a <code>QueuedResponseData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QueuedResponseData} obj Optional instance to populate.
     * @return {module:model/QueuedResponseData} The populated <code>QueuedResponseData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QueuedResponseData();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>QueuedResponseData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>QueuedResponseData</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of QueuedResponseData.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }

        return true;
    }

/**
     * Returns Success response message or error details.
     * @return {String}
     */
    getMessage() {
        return this.message;
    }

    /**
     * Sets Success response message or error details.
     * @param {String} message Success response message or error details.
     */
    setMessage(message) {
        this['message'] = message;
        return this;
    }
/**
     * Returns The id of the render task in UUID format.
     * @return {String}
     */
    getId() {
        return this.id;
    }

    /**
     * Sets The id of the render task in UUID format.
     * @param {String} id The id of the render task in UUID format.
     */
    setId(id) {
        this['id'] = id;
        return this;
    }

}

QueuedResponseData.RequiredProperties = ["message", "id"];

/**
 * Success response message or error details.
 * @member {String} message
 */
QueuedResponseData.prototype['message'] = undefined;

/**
 * The id of the render task in UUID format.
 * @member {String} id
 */
QueuedResponseData.prototype['id'] = undefined;






export default QueuedResponseData;

