"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = void 0;
var _ApiClient = _interopRequireDefault(require("../ApiClient"));
function _interopRequireDefault(e) { return e && e.__esModule ? e : { "default": e }; }
function _typeof(o) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (o) { return typeof o; } : function (o) { return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o; }, _typeof(o); }
function _createForOfIteratorHelper(r, e) { var t = "undefined" != typeof Symbol && r[Symbol.iterator] || r["@@iterator"]; if (!t) { if (Array.isArray(r) || (t = _unsupportedIterableToArray(r)) || e && r && "number" == typeof r.length) { t && (r = t); var _n = 0, F = function F() {}; return { s: F, n: function n() { return _n >= r.length ? { done: !0 } : { done: !1, value: r[_n++] }; }, e: function e(r) { throw r; }, f: F }; } throw new TypeError("Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method."); } var o, a = !0, u = !1; return { s: function s() { t = t.call(r); }, n: function n() { var r = t.next(); return a = r.done, r; }, e: function e(r) { u = !0, o = r; }, f: function f() { try { a || null == t["return"] || t["return"](); } finally { if (u) throw o; } } }; }
function _unsupportedIterableToArray(r, a) { if (r) { if ("string" == typeof r) return _arrayLikeToArray(r, a); var t = {}.toString.call(r).slice(8, -1); return "Object" === t && r.constructor && (t = r.constructor.name), "Map" === t || "Set" === t ? Array.from(r) : "Arguments" === t || /^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(t) ? _arrayLikeToArray(r, a) : void 0; } }
function _arrayLikeToArray(r, a) { (null == a || a > r.length) && (a = r.length); for (var e = 0, n = Array(a); e < a; e++) n[e] = r[e]; return n; }
function _classCallCheck(a, n) { if (!(a instanceof n)) throw new TypeError("Cannot call a class as a function"); }
function _defineProperties(e, r) { for (var t = 0; t < r.length; t++) { var o = r[t]; o.enumerable = o.enumerable || !1, o.configurable = !0, "value" in o && (o.writable = !0), Object.defineProperty(e, _toPropertyKey(o.key), o); } }
function _createClass(e, r, t) { return r && _defineProperties(e.prototype, r), t && _defineProperties(e, t), Object.defineProperty(e, "prototype", { writable: !1 }), e; }
function _toPropertyKey(t) { var i = _toPrimitive(t, "string"); return "symbol" == _typeof(i) ? i : i + ""; }
function _toPrimitive(t, r) { if ("object" != _typeof(t) || !t) return t; var e = t[Symbol.toPrimitive]; if (void 0 !== e) { var i = e.call(t, r || "default"); if ("object" != _typeof(i)) return i; throw new TypeError("@@toPrimitive must return a primitive value."); } return ("string" === r ? String : Number)(t); } /**
 * Shotstack
 * Official Node SDK for the Shotstack Cloud Video Editing API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * The ShotstackTextToImageOptions model module.
 * @module model/ShotstackTextToImageOptions
 * @version 0.2.9
 */
var ShotstackTextToImageOptions = /*#__PURE__*/function () {
  /**
   * Constructs a new <code>ShotstackTextToImageOptions</code>.
   * Options for the Shotstack text-to-image service. Set a text prompt to generate an image from. The output will be  generated as a PNG file available at the URL returned in the response.
   * @alias module:model/ShotstackTextToImageOptions
   * @param type {module:model/ShotstackTextToImageOptions.TypeEnum} The type of asset to generate - set to `text-to-image` for text-to-image.
   * @param prompt {String} The text prompt to generate an image from.
   * @param width {Number} The width of the image in pixels.
   * @param height {Number} The height of the image in pixels.
   */
  function ShotstackTextToImageOptions(type, prompt, width, height) {
    _classCallCheck(this, ShotstackTextToImageOptions);
    ShotstackTextToImageOptions.initialize(this, type, prompt, width, height);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  return _createClass(ShotstackTextToImageOptions, [{
    key: "getType",
    value:
    /**
         * Returns The type of asset to generate - set to `text-to-image` for text-to-image.
         * @return {module:model/ShotstackTextToImageOptions.TypeEnum}
         */
    function getType() {
      return this.type;
    }

    /**
     * Sets The type of asset to generate - set to `text-to-image` for text-to-image.
     * @param {module:model/ShotstackTextToImageOptions.TypeEnum} type The type of asset to generate - set to `text-to-image` for text-to-image.
     */
  }, {
    key: "setType",
    value: function setType(type) {
      this['type'] = type;
      return this;
    }
    /**
         * Returns The text prompt to generate an image from.
         * @return {String}
         */
  }, {
    key: "getPrompt",
    value: function getPrompt() {
      return this.prompt;
    }

    /**
     * Sets The text prompt to generate an image from.
     * @param {String} prompt The text prompt to generate an image from.
     */
  }, {
    key: "setPrompt",
    value: function setPrompt(prompt) {
      this['prompt'] = prompt;
      return this;
    }
    /**
         * Returns The width of the image in pixels.
         * @return {Number}
         */
  }, {
    key: "getWidth",
    value: function getWidth() {
      return this.width;
    }

    /**
     * Sets The width of the image in pixels.
     * @param {Number} width The width of the image in pixels.
     */
  }, {
    key: "setWidth",
    value: function setWidth(width) {
      this['width'] = width;
      return this;
    }
    /**
         * Returns The height of the image in pixels.
         * @return {Number}
         */
  }, {
    key: "getHeight",
    value: function getHeight() {
      return this.height;
    }

    /**
     * Sets The height of the image in pixels.
     * @param {Number} height The height of the image in pixels.
     */
  }, {
    key: "setHeight",
    value: function setHeight(height) {
      this['height'] = height;
      return this;
    }
  }], [{
    key: "initialize",
    value: function initialize(obj, type, prompt, width, height) {
      obj['type'] = type || 'text-to-image';
      obj['prompt'] = prompt;
      obj['width'] = width;
      obj['height'] = height;
    }

    /**
     * Constructs a <code>ShotstackTextToImageOptions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ShotstackTextToImageOptions} obj Optional instance to populate.
     * @return {module:model/ShotstackTextToImageOptions} The populated <code>ShotstackTextToImageOptions</code> instance.
     */
  }, {
    key: "constructFromObject",
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new ShotstackTextToImageOptions();
        if (data.hasOwnProperty('type')) {
          obj['type'] = _ApiClient["default"].convertToType(data['type'], 'String');
        }
        if (data.hasOwnProperty('prompt')) {
          obj['prompt'] = _ApiClient["default"].convertToType(data['prompt'], 'String');
        }
        if (data.hasOwnProperty('width')) {
          obj['width'] = _ApiClient["default"].convertToType(data['width'], 'Number');
        }
        if (data.hasOwnProperty('height')) {
          obj['height'] = _ApiClient["default"].convertToType(data['height'], 'Number');
        }
      }
      return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ShotstackTextToImageOptions</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ShotstackTextToImageOptions</code>.
     */
  }, {
    key: "validateJSON",
    value: function validateJSON(data) {
      // check to make sure all required properties are present in the JSON string
      var _iterator = _createForOfIteratorHelper(ShotstackTextToImageOptions.RequiredProperties),
        _step;
      try {
        for (_iterator.s(); !(_step = _iterator.n()).done;) {
          var property = _step.value;
          if (!data.hasOwnProperty(property)) {
            throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
          }
        }
        // ensure the json data is a string
      } catch (err) {
        _iterator.e(err);
      } finally {
        _iterator.f();
      }
      if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
        throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
      }
      // ensure the json data is a string
      if (data['prompt'] && !(typeof data['prompt'] === 'string' || data['prompt'] instanceof String)) {
        throw new Error("Expected the field `prompt` to be a primitive type in the JSON string but got " + data['prompt']);
      }
      return true;
    }
  }]);
}();
ShotstackTextToImageOptions.RequiredProperties = ["type", "prompt", "width", "height"];

/**
 * The type of asset to generate - set to `text-to-image` for text-to-image.
 * @member {module:model/ShotstackTextToImageOptions.TypeEnum} type
 * @default 'text-to-image'
 */
ShotstackTextToImageOptions.prototype['type'] = 'text-to-image';

/**
 * The text prompt to generate an image from.
 * @member {String} prompt
 */
ShotstackTextToImageOptions.prototype['prompt'] = undefined;

/**
 * The width of the image in pixels.
 * @member {Number} width
 */
ShotstackTextToImageOptions.prototype['width'] = undefined;

/**
 * The height of the image in pixels.
 * @member {Number} height
 */
ShotstackTextToImageOptions.prototype['height'] = undefined;

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
ShotstackTextToImageOptions['TypeEnum'] = {
  /**
   * value: "text-to-image"
   * @const
   */
  "text-to-image": "text-to-image"
};
var _default = exports["default"] = ShotstackTextToImageOptions;