"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = void 0;
var _ApiClient = _interopRequireDefault(require("../ApiClient"));
var _Tween = _interopRequireDefault(require("./Tween"));
var _SkewTransformationY;
function _interopRequireDefault(e) { return e && e.__esModule ? e : { "default": e }; }
function _typeof(o) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (o) { return typeof o; } : function (o) { return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o; }, _typeof(o); }
function _classCallCheck(a, n) { if (!(a instanceof n)) throw new TypeError("Cannot call a class as a function"); }
function _defineProperties(e, r) { for (var t = 0; t < r.length; t++) { var o = r[t]; o.enumerable = o.enumerable || !1, o.configurable = !0, "value" in o && (o.writable = !0), Object.defineProperty(e, _toPropertyKey(o.key), o); } }
function _createClass(e, r, t) { return r && _defineProperties(e.prototype, r), t && _defineProperties(e, t), Object.defineProperty(e, "prototype", { writable: !1 }), e; }
function _defineProperty(e, r, t) { return (r = _toPropertyKey(r)) in e ? Object.defineProperty(e, r, { value: t, enumerable: !0, configurable: !0, writable: !0 }) : e[r] = t, e; }
function _toPropertyKey(t) { var i = _toPrimitive(t, "string"); return "symbol" == _typeof(i) ? i : i + ""; }
function _toPrimitive(t, r) { if ("object" != _typeof(t) || !t) return t; var e = t[Symbol.toPrimitive]; if (void 0 !== e) { var i = e.call(t, r || "default"); if ("object" != _typeof(i)) return i; throw new TypeError("@@toPrimitive must return a primitive value."); } return ("string" === r ? String : Number)(t); } /**
 * Shotstack
 * Official Node SDK for the Shotstack Cloud Video Editing API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * The SkewTransformationY model module.
 * @module model/SkewTransformationY
 * @version 0.2.9
 */
var SkewTransformationY = /*#__PURE__*/function () {
  /**
   * Constructs a new <code>SkewTransformationY</code>.
   * Skew the clip along it&#39;s y axis.
   * @alias module:model/SkewTransformationY
   * @param {(module:model/Number|module:model/[Tween])} instance The actual instance to initialize SkewTransformationY.
   */
  function SkewTransformationY() {
    var instance = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : null;
    _classCallCheck(this, SkewTransformationY);
    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    _defineProperty(this, "toJSON", function () {
      return this.getActualInstance();
    });
    if (instance === null) {
      this.actualInstance = null;
      return;
    }
    var match = 0;
    var errorMessages = [];
    // Range varies from 0 to 3. Positive numbers skew the asset up, negative down. The distance moved is relative to the height of the viewport - i.e. an Y skew of 0.5 will skew the asset half the screen height up.
    try {
      this.actualInstance = instance;
      match++;
    } catch (err) {
      // json data failed to deserialize into Number
      errorMessages.push("Failed to construct Number: " + err);
    }

    // An array of [Tween](./#tocs_tween) objects used to create a custom animation. Animate the Y skew of an asset over time.
    try {
      if (typeof instance === "[Tween]") {
        this.actualInstance = instance;
      } else {
        // plain JS object
        // validate the object
        [_Tween["default"]].validateJSON(instance); // throw an exception if no match
        // create [Tween] from JS object
        this.actualInstance = [_Tween["default"]].constructFromObject(instance);
      }
      match++;
    } catch (err) {
      // json data failed to deserialize into [Tween]
      errorMessages.push("Failed to construct [Tween]: " + err);
    }
    if (match > 1) {
      throw new Error("Multiple matches found constructing `SkewTransformationY` with oneOf schemas Number, [Tween]. Input: " + JSON.stringify(instance));
    } else if (match === 0) {
      this.actualInstance = null; // clear the actual instance in case there are multiple matches
      throw new Error("No match found constructing `SkewTransformationY` with oneOf schemas Number, [Tween]. Details: " + errorMessages.join(", "));
    } else {// only 1 match
      // the input is valid
    }
  }

  /**
   * Constructs a <code>SkewTransformationY</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SkewTransformationY} obj Optional instance to populate.
   * @return {module:model/SkewTransformationY} The populated <code>SkewTransformationY</code> instance.
   */
  return _createClass(SkewTransformationY, [{
    key: "getActualInstance",
    value:
    /**
     * Gets the actual instance, which can be <code>Number</code>, <code>[Tween]</code>.
     * @return {(module:model/Number|module:model/[Tween])} The actual instance.
     */
    function getActualInstance() {
      return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>Number</code>, <code>[Tween]</code>.
     * @param {(module:model/Number|module:model/[Tween])} obj The actual instance.
     */
  }, {
    key: "setActualInstance",
    value: function setActualInstance(obj) {
      this.actualInstance = SkewTransformationY.constructFromObject(obj).getActualInstance();
    }
  }], [{
    key: "constructFromObject",
    value: function constructFromObject(data, obj) {
      return new SkewTransformationY(data);
    }
  }]);
}();
_SkewTransformationY = SkewTransformationY;
/**
 * Create an instance of SkewTransformationY from a JSON string.
 * @param {string} json_string JSON string.
 * @return {module:model/SkewTransformationY} An instance of SkewTransformationY.
 */
_defineProperty(SkewTransformationY, "fromJSON", function (json_string) {
  return _SkewTransformationY.constructFromObject(JSON.parse(json_string));
});
SkewTransformationY.OneOf = ["Number", "[Tween]"];
var _default = exports["default"] = SkewTransformationY;