/**
 * Shotstack
 * Official Node SDK for the Shotstack Cloud Video Editing API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SourceResponseData from './SourceResponseData';

/**
 * The SourceResponse model module.
 * @module model/SourceResponse
 * @version 0.2.6
 */
class SourceResponse {
    /**
     * Constructs a new <code>SourceResponse</code>.
     * The response returned by the Ingest API [get source](#get-source) request. Includes details of the ingested source file. The response follows the [json:api](https://jsonapi.org/) specification.
     * @alias module:model/SourceResponse
     * @param data {module:model/SourceResponseData} 
     */
    constructor(data) { 
        
        SourceResponse.initialize(this, data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, data) { 
        obj['data'] = data;
    }

    /**
     * Constructs a <code>SourceResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SourceResponse} obj Optional instance to populate.
     * @return {module:model/SourceResponse} The populated <code>SourceResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SourceResponse();

            if (data.hasOwnProperty('data')) {
                obj['data'] = SourceResponseData.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SourceResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SourceResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SourceResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `data`
        if (data['data']) { // data not null
          SourceResponseData.validateJSON(data['data']);
        }

        return true;
    }

/**
     * @return {module:model/SourceResponseData}
     */
    getData() {
        return this.data;
    }

    /**
     * @param {module:model/SourceResponseData} data
     */
    setData(data) {
        this['data'] = data;
        return this;
    }

}

SourceResponse.RequiredProperties = ["data"];

/**
 * @member {module:model/SourceResponseData} data
 */
SourceResponse.prototype['data'] = undefined;






export default SourceResponse;

