/**
 * Shotstack
 * Official Node SDK for the Shotstack Cloud Video Editing API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SourceResponseData from './SourceResponseData';

/**
 * The SourceListResponse model module.
 * @module model/SourceListResponse
 * @version 0.2.6
 */
class SourceListResponse {
    /**
     * Constructs a new <code>SourceListResponse</code>.
     * A list of all ingested source files fetched or uploaded to a users account.
     * @alias module:model/SourceListResponse
     * @param data {Array.<module:model/SourceResponseData>} An array of ingested source files.
     */
    constructor(data) { 
        
        SourceListResponse.initialize(this, data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, data) { 
        obj['data'] = data;
    }

    /**
     * Constructs a <code>SourceListResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SourceListResponse} obj Optional instance to populate.
     * @return {module:model/SourceListResponse} The populated <code>SourceListResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SourceListResponse();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [SourceResponseData]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SourceListResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SourceListResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SourceListResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['data']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['data'])) {
                throw new Error("Expected the field `data` to be an array in the JSON data but got " + data['data']);
            }
            // validate the optional field `data` (array)
            for (const item of data['data']) {
                SourceResponseData.validateJSON(item);
            };
        }

        return true;
    }

/**
     * Returns An array of ingested source files.
     * @return {Array.<module:model/SourceResponseData>}
     */
    getData() {
        return this.data;
    }

    /**
     * Sets An array of ingested source files.
     * @param {Array.<module:model/SourceResponseData>} data An array of ingested source files.
     */
    setData(data) {
        this['data'] = data;
        return this;
    }

}

SourceListResponse.RequiredProperties = ["data"];

/**
 * An array of ingested source files.
 * @member {Array.<module:model/SourceResponseData>} data
 */
SourceListResponse.prototype['data'] = undefined;






export default SourceListResponse;

