"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = void 0;
var _ApiClient = _interopRequireDefault(require("../ApiClient"));
var _TransferResponseAttributes = _interopRequireDefault(require("./TransferResponseAttributes"));
function _interopRequireDefault(e) { return e && e.__esModule ? e : { "default": e }; }
function _typeof(o) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (o) { return typeof o; } : function (o) { return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o; }, _typeof(o); }
function _classCallCheck(a, n) { if (!(a instanceof n)) throw new TypeError("Cannot call a class as a function"); }
function _defineProperties(e, r) { for (var t = 0; t < r.length; t++) { var o = r[t]; o.enumerable = o.enumerable || !1, o.configurable = !0, "value" in o && (o.writable = !0), Object.defineProperty(e, _toPropertyKey(o.key), o); } }
function _createClass(e, r, t) { return r && _defineProperties(e.prototype, r), t && _defineProperties(e, t), Object.defineProperty(e, "prototype", { writable: !1 }), e; }
function _toPropertyKey(t) { var i = _toPrimitive(t, "string"); return "symbol" == _typeof(i) ? i : i + ""; }
function _toPrimitive(t, r) { if ("object" != _typeof(t) || !t) return t; var e = t[Symbol.toPrimitive]; if (void 0 !== e) { var i = e.call(t, r || "default"); if ("object" != _typeof(i)) return i; throw new TypeError("@@toPrimitive must return a primitive value."); } return ("string" === r ? String : Number)(t); } /**
 * Shotstack
 * Official Node SDK for the Shotstack Cloud Video Editing API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * The TransferResponseData model module.
 * @module model/TransferResponseData
 * @version 0.2.9
 */
var TransferResponseData = /*#__PURE__*/function () {
  /**
   * Constructs a new <code>TransferResponseData</code>.
   * The type of resource (an asset) and the transfer attributes. Returned with [TransferResponse](#tocs_transferresponse).
   * @alias module:model/TransferResponseData
   */
  function TransferResponseData() {
    _classCallCheck(this, TransferResponseData);
    TransferResponseData.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  return _createClass(TransferResponseData, [{
    key: "getType",
    value:
    /**
         * Returns The type of resource, in this case it is an asset.
         * @return {String}
         */
    function getType() {
      return this.type;
    }

    /**
     * Sets The type of resource, in this case it is an asset.
     * @param {String} type The type of resource, in this case it is an asset.
     */
  }, {
    key: "setType",
    value: function setType(type) {
      this['type'] = type;
      return this;
    }
    /**
         * @return {module:model/TransferResponseAttributes}
         */
  }, {
    key: "getAttributes",
    value: function getAttributes() {
      return this.attributes;
    }

    /**
     * @param {module:model/TransferResponseAttributes} attributes
     */
  }, {
    key: "setAttributes",
    value: function setAttributes(attributes) {
      this['attributes'] = attributes;
      return this;
    }
  }], [{
    key: "initialize",
    value: function initialize(obj) {}

    /**
     * Constructs a <code>TransferResponseData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TransferResponseData} obj Optional instance to populate.
     * @return {module:model/TransferResponseData} The populated <code>TransferResponseData</code> instance.
     */
  }, {
    key: "constructFromObject",
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new TransferResponseData();
        if (data.hasOwnProperty('type')) {
          obj['type'] = _ApiClient["default"].convertToType(data['type'], 'String');
        }
        if (data.hasOwnProperty('attributes')) {
          obj['attributes'] = _TransferResponseAttributes["default"].constructFromObject(data['attributes']);
        }
      }
      return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TransferResponseData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TransferResponseData</code>.
     */
  }, {
    key: "validateJSON",
    value: function validateJSON(data) {
      // ensure the json data is a string
      if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
        throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
      }
      // validate the optional field `attributes`
      if (data['attributes']) {
        // data not null
        _TransferResponseAttributes["default"].validateJSON(data['attributes']);
      }
      return true;
    }
  }]);
}();
/**
 * The type of resource, in this case it is an asset.
 * @member {String} type
 */
TransferResponseData.prototype['type'] = undefined;

/**
 * @member {module:model/TransferResponseAttributes} attributes
 */
TransferResponseData.prototype['attributes'] = undefined;
var _default = exports["default"] = TransferResponseData;