/**
 * Shotstack
 * Official Node SDK for the Shotstack Cloud Video Editing API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UploadResponseAttributes from './UploadResponseAttributes';

/**
 * The UploadResponseData model module.
 * @module model/UploadResponseData
 * @version 0.2.6
 */
class UploadResponseData {
    /**
     * Constructs a new <code>UploadResponseData</code>.
     * The type of resource (an upload), it&#39;s id and attributes of the upload request.
     * @alias module:model/UploadResponseData
     * @param type {String} The type of resource, in this case it is an upload.
     * @param id {String} The upload file id.
     * @param attributes {module:model/UploadResponseAttributes} 
     */
    constructor(type, id, attributes) { 
        
        UploadResponseData.initialize(this, type, id, attributes);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, id, attributes) { 
        obj['type'] = type;
        obj['id'] = id;
        obj['attributes'] = attributes;
    }

    /**
     * Constructs a <code>UploadResponseData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UploadResponseData} obj Optional instance to populate.
     * @return {module:model/UploadResponseData} The populated <code>UploadResponseData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UploadResponseData();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = UploadResponseAttributes.constructFromObject(data['attributes']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UploadResponseData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UploadResponseData</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UploadResponseData.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // validate the optional field `attributes`
        if (data['attributes']) { // data not null
          UploadResponseAttributes.validateJSON(data['attributes']);
        }

        return true;
    }

/**
     * Returns The type of resource, in this case it is an upload.
     * @return {String}
     */
    getType() {
        return this.type;
    }

    /**
     * Sets The type of resource, in this case it is an upload.
     * @param {String} type The type of resource, in this case it is an upload.
     */
    setType(type) {
        this['type'] = type;
        return this;
    }
/**
     * Returns The upload file id.
     * @return {String}
     */
    getId() {
        return this.id;
    }

    /**
     * Sets The upload file id.
     * @param {String} id The upload file id.
     */
    setId(id) {
        this['id'] = id;
        return this;
    }
/**
     * @return {module:model/UploadResponseAttributes}
     */
    getAttributes() {
        return this.attributes;
    }

    /**
     * @param {module:model/UploadResponseAttributes} attributes
     */
    setAttributes(attributes) {
        this['attributes'] = attributes;
        return this;
    }

}

UploadResponseData.RequiredProperties = ["type", "id", "attributes"];

/**
 * The type of resource, in this case it is an upload.
 * @member {String} type
 */
UploadResponseData.prototype['type'] = undefined;

/**
 * The upload file id.
 * @member {String} id
 */
UploadResponseData.prototype['id'] = undefined;

/**
 * @member {module:model/UploadResponseAttributes} attributes
 */
UploadResponseData.prototype['attributes'] = undefined;






export default UploadResponseData;

